name: fastlog
description: A super lightweight and high-performance logging package for Dart and Flutter.
version: 0.1.0
repository: https://github.com/cas8398/flutter-fastlog
homepage: https://github.com/cas8398/flutter-fastlog
issue_tracker: https://github.com/cas8398/flutter-fastlog/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.10.0
  intl: ^0.20.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
