name: flutter_fastlog
description: A super lightweight and high-performance logging, Supports customizable log levels, colors, timestamps, tag, and emojis.
version: 0.1.6
repository: https://github.com/cas8398/flutter-fastlog
homepage: https://github.com/cas8398/flutter-fastlog
issue_tracker: https://github.com/cas8398/flutter-fastlog/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.10.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

topics:
  - logger
  - log
  - logging
  - color
